import { NextResponse } from 'next/server';
import { connectDb } from '@/lib/mongodb';
import { requireAuth } from '@/lib/rbac';
import { AppError } from '@/lib/errors';
import { callGroq } from '@/lib/ai/groq';

export async function POST(request) {
  try {
    const token = await requireAuth(request);
    
    // Only students can submit assignments for plagiarism check
    if (token.role !== 'student') {
      throw new AppError('Forbidden: Only students can submit assignments', 403);
    }

    const { title, content, assignmentId } = await request.json();

    if (!content || !title) {
      throw new AppError('Title and content are required', 400);
    }

    // Call Groq AI to analyze plagiarism/originality
    const prompt = `
You are an expert AI Plagiarism and Originality Detector.
Analyze the following student assignment submission.
Determine the likelihood that the text was copied from online sources or generated by an AI.
Provide an originality score from 0 to 100 (where 100 means completely original, 0 means entirely copied/AI-generated).
Also provide a brief justification report (2-3 sentences) explaining your reasoning.

Format your response strictly as JSON with two keys:
{
  "score": number,
  "report": "string"
}

Student Submission:
${content}
    `;

    let aiResponseText = await callGroq(prompt, [], token.uid);
    let aiData;
    
    try {
      // Attempt to parse JSON. Sometimes LLMs wrap in markdown code blocks.
      aiResponseText = aiResponseText.replace(/```json/g, '').replace(/```/g, '').trim();
      aiData = JSON.parse(aiResponseText);
    } catch (e) {
      console.error('Failed to parse AI response as JSON:', aiResponseText);
      aiData = { score: 50, report: "Error parsing AI response. Needs manual review." };
    }

    const db = await connectDb();
    const collection = db.collection('assignments');

    const newSubmission = {
      studentId: token.uid,
      studentName: token.name || 'Student',
      assignmentId: assignmentId || 'general',
      title,
      content,
      originalityScore: aiData.score,
      originalityReport: aiData.report,
      submittedAt: new Date(),
    };

    const result = await collection.insertOne(newSubmission);

    return NextResponse.json({ 
      success: true, 
      message: 'Assignment submitted successfully',
      submissionId: result.insertedId,
      // We purposefully don't return the score to the student here to prevent gaming
    });

  } catch (error) {
    console.error('Assignment Submit Error:', error);
    const status = error.statusCode || 500;
    return NextResponse.json(
      { success: false, error: error.message || 'Internal Server Error' },
      { status }
    );
  }
}
